@include('templates.show.row',['label' => 'NIP','value' => $entity[isset($prefix) && $prefix ? $prefix.'_nip' : 'nip']])
@include('templates.show.row',['label' => 'Nazwa','value' => $entity[isset($prefix) && $prefix ? $prefix.'_name' : 'name']])
@include('templates.show.row',['label' => 'Adres','value' => $entity[isset($prefix) && $prefix ? $prefix.'_address' : 'address']])
@include('templates.show.row',['label' => 'Kod pocztowy','value' => $entity[isset($prefix) && $prefix ? $prefix.'_postcode' : 'postcode']])
@include('templates.show.row',['label' => 'Miasto','value' => $entity[isset($prefix) && $prefix ? $prefix.'_city' : 'city']])
